from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1011, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(350, 10, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.RadioButtonCreate = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButtonCreate.setGeometry(QtCore.QRect(10, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.RadioButtonCreate.setFont(font)
        self.RadioButtonCreate.setObjectName("RadioButtonCreate")
        self.RadioButtonTest = QtWidgets.QRadioButton(self.groupBox)
        self.RadioButtonTest.setGeometry(QtCore.QRect(160, 30, 121, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.RadioButtonTest.setFont(font)
        self.RadioButtonTest.setObjectName("RadioButtonTest")
        self.TableWidgetMatrixIn = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetMatrixIn.setEnabled(False)
        self.TableWidgetMatrixIn.setGeometry(QtCore.QRect(70, 20, 251, 141))
        self.TableWidgetMatrixIn.setObjectName("TableWidgetMatrixIn")
        self.TableWidgetMatrixIn.setColumnCount(0)
        self.TableWidgetMatrixIn.setRowCount(0)
        self.LabelColumns = QtWidgets.QLabel(self.centralwidget)
        self.LabelColumns.setEnabled(False)
        self.LabelColumns.setGeometry(QtCore.QRect(680, 20, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelColumns.setFont(font)
        self.LabelColumns.setObjectName("LabelColumns")
        self.LabelRows = QtWidgets.QLabel(self.centralwidget)
        self.LabelRows.setEnabled(False)
        self.LabelRows.setGeometry(QtCore.QRect(680, 50, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelRows.setFont(font)
        self.LabelRows.setObjectName("LabelRows")
        self.SpinBoxColumns = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxColumns.setEnabled(False)
        self.SpinBoxColumns.setGeometry(QtCore.QRect(930, 20, 42, 22))
        self.SpinBoxColumns.setObjectName("SpinBoxColumns")
        self.SpinBoxRows = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxRows.setEnabled(False)
        self.SpinBoxRows.setGeometry(QtCore.QRect(930, 50, 42, 22))
        self.SpinBoxRows.setObjectName("SpinBoxRows")
        self.LabelMatrixIn = QtWidgets.QLabel(self.centralwidget)
        self.LabelMatrixIn.setEnabled(False)
        self.LabelMatrixIn.setGeometry(QtCore.QRect(20, 70, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelMatrixIn.setFont(font)
        self.LabelMatrixIn.setObjectName("LabelMatrixIn")
        self.PushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonStart.setEnabled(False)
        self.PushButtonStart.setGeometry(QtCore.QRect(350, 80, 291, 23))
        self.PushButtonStart.setObjectName("PushButtonStart")
        self.LabelLengthCW = QtWidgets.QLabel(self.centralwidget)
        self.LabelLengthCW.setEnabled(False)
        self.LabelLengthCW.setGeometry(QtCore.QRect(660, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelLengthCW.setFont(font)
        self.LabelLengthCW.setObjectName("LabelLengthCW")
        self.LabelLengthIW = QtWidgets.QLabel(self.centralwidget)
        self.LabelLengthIW.setEnabled(False)
        self.LabelLengthIW.setGeometry(QtCore.QRect(760, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelLengthIW.setFont(font)
        self.LabelLengthIW.setObjectName("LabelLengthIW")
        self.TableWidgetMatrixInSys = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetMatrixInSys.setEnabled(False)
        self.TableWidgetMatrixInSys.setGeometry(QtCore.QRect(70, 180, 251, 141))
        self.TableWidgetMatrixInSys.setObjectName("TableWidgetMatrixInSys")
        self.TableWidgetMatrixInSys.setColumnCount(0)
        self.TableWidgetMatrixInSys.setRowCount(0)
        self.LabelMatrixInSys = QtWidgets.QLabel(self.centralwidget)
        self.LabelMatrixInSys.setEnabled(False)
        self.LabelMatrixInSys.setGeometry(QtCore.QRect(10, 230, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelMatrixInSys.setFont(font)
        self.LabelMatrixInSys.setObjectName("LabelMatrixInSys")
        self.TableWidgetMatrixSys = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetMatrixSys.setEnabled(False)
        self.TableWidgetMatrixSys.setGeometry(QtCore.QRect(70, 340, 251, 141))
        self.TableWidgetMatrixSys.setObjectName("TableWidgetMatrixSys")
        self.TableWidgetMatrixSys.setColumnCount(0)
        self.TableWidgetMatrixSys.setRowCount(0)
        self.LabelMatrixSys = QtWidgets.QLabel(self.centralwidget)
        self.LabelMatrixSys.setEnabled(False)
        self.LabelMatrixSys.setGeometry(QtCore.QRect(10, 390, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelMatrixSys.setFont(font)
        self.LabelMatrixSys.setObjectName("LabelMatrixSys")
        self.LabelTableCW = QtWidgets.QLabel(self.centralwidget)
        self.LabelTableCW.setEnabled(False)
        self.LabelTableCW.setGeometry(QtCore.QRect(410, 110, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelTableCW.setFont(font)
        self.LabelTableCW.setObjectName("LabelTableCW")
        self.TableWidgetTableCW = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetTableCW.setEnabled(False)
        self.TableWidgetTableCW.setGeometry(QtCore.QRect(350, 140, 291, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.TableWidgetTableCW.sizePolicy().hasHeightForWidth())
        self.TableWidgetTableCW.setSizePolicy(sizePolicy)
        self.TableWidgetTableCW.setObjectName("TableWidgetTableCW")
        self.TableWidgetTableCW.setColumnCount(0)
        self.TableWidgetTableCW.setRowCount(0)
        self.LabelTableHWMin = QtWidgets.QLabel(self.centralwidget)
        self.LabelTableHWMin.setEnabled(False)
        self.LabelTableHWMin.setGeometry(QtCore.QRect(880, 110, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelTableHWMin.setFont(font)
        self.LabelTableHWMin.setObjectName("LabelTableHWMin")
        self.LabelTableCountCorEr = QtWidgets.QLabel(self.centralwidget)
        self.LabelTableCountCorEr.setEnabled(False)
        self.LabelTableCountCorEr.setGeometry(QtCore.QRect(660, 170, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelTableCountCorEr.setFont(font)
        self.LabelTableCountCorEr.setObjectName("LabelTableCountCorEr")
        self.LabelTableFindEr = QtWidgets.QLabel(self.centralwidget)
        self.LabelTableFindEr.setEnabled(False)
        self.LabelTableFindEr.setGeometry(QtCore.QRect(660, 140, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelTableFindEr.setFont(font)
        self.LabelTableFindEr.setObjectName("LabelTableFindEr")
        self.LabelWordInput = QtWidgets.QLabel(self.centralwidget)
        self.LabelWordInput.setEnabled(False)
        self.LabelWordInput.setGeometry(QtCore.QRect(740, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelWordInput.setFont(font)
        self.LabelWordInput.setObjectName("LabelWordInput")
        self.TextEditWordInput = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditWordInput.setEnabled(False)
        self.TextEditWordInput.setGeometry(QtCore.QRect(660, 230, 341, 31))
        self.TextEditWordInput.setObjectName("TextEditWordInput")
        self.PushButtonDecode = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonDecode.setEnabled(False)
        self.PushButtonDecode.setGeometry(QtCore.QRect(740, 270, 171, 23))
        self.PushButtonDecode.setObjectName("PushButtonDecode")
        self.LabelTableSE = QtWidgets.QLabel(self.centralwidget)
        self.LabelTableSE.setEnabled(False)
        self.LabelTableSE.setGeometry(QtCore.QRect(350, 310, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelTableSE.setFont(font)
        self.LabelTableSE.setObjectName("LabelTableSE")
        self.TableWidgetTableSE = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetTableSE.setEnabled(False)
        self.TableWidgetTableSE.setGeometry(QtCore.QRect(350, 340, 291, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.TableWidgetTableSE.sizePolicy().hasHeightForWidth())
        self.TableWidgetTableSE.setSizePolicy(sizePolicy)
        self.TableWidgetTableSE.setObjectName("TableWidgetTableSE")
        self.TableWidgetTableSE.setColumnCount(0)
        self.TableWidgetTableSE.setRowCount(0)
        self.LabelSyndrom = QtWidgets.QLabel(self.centralwidget)
        self.LabelSyndrom.setEnabled(False)
        self.LabelSyndrom.setGeometry(QtCore.QRect(660, 310, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelSyndrom.setFont(font)
        self.LabelSyndrom.setObjectName("LabelSyndrom")
        self.LabelErrorVector = QtWidgets.QLabel(self.centralwidget)
        self.LabelErrorVector.setEnabled(False)
        self.LabelErrorVector.setGeometry(QtCore.QRect(660, 340, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelErrorVector.setFont(font)
        self.LabelErrorVector.setObjectName("LabelErrorVector")
        self.LabelCW = QtWidgets.QLabel(self.centralwidget)
        self.LabelCW.setEnabled(False)
        self.LabelCW.setGeometry(QtCore.QRect(660, 370, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelCW.setFont(font)
        self.LabelCW.setObjectName("LabelCW")
        self.LabelIW = QtWidgets.QLabel(self.centralwidget)
        self.LabelIW.setEnabled(False)
        self.LabelIW.setGeometry(QtCore.QRect(660, 400, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelIW.setFont(font)
        self.LabelIW.setObjectName("LabelIW")
        self.PushButtonCreateMatrix = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonCreateMatrix.setEnabled(False)
        self.PushButtonCreateMatrix.setGeometry(QtCore.QRect(680, 80, 291, 23))
        self.PushButtonCreateMatrix.setObjectName("PushButtonCreateMatrix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matrix representation of block codes"))
        self.groupBox.setTitle(_translate("MainWindow", "Выберите тип входной матрицы"))
        self.RadioButtonCreate.setText(_translate("MainWindow", "Порождающая"))
        self.RadioButtonTest.setText(_translate("MainWindow", "Проверочная"))
        self.LabelColumns.setText(_translate("MainWindow", "Выберите количество колонок:"))
        self.LabelRows.setText(_translate("MainWindow", "Выберите количество строк:"))
        self.LabelMatrixIn.setText(_translate("MainWindow", "# = "))
        self.PushButtonStart.setText(_translate("MainWindow", "Начать матричные преобразования кода"))
        self.LabelLengthCW.setText(_translate("MainWindow", "n ="))
        self.LabelLengthIW.setText(_translate("MainWindow", "k ="))
        self.LabelMatrixInSys.setText(_translate("MainWindow", "<html><head/><body><p>#<span style=\" vertical-align:sub;\">sys</span> = </p></body></html>"))
        self.LabelMatrixSys.setText(_translate("MainWindow", "<html><head/><body><p>!<span style=\" vertical-align:sub;\">sys</span> = </p></body></html>"))
        self.LabelTableCW.setText(_translate("MainWindow", "Таблица кодовых слов"))
        self.LabelTableHWMin.setText(_translate("MainWindow", "<html><head/><body><p>d<span style=\" vertical-align:sub;\">min</span> = </p></body></html>"))
        self.LabelTableCountCorEr.setText(_translate("MainWindow", "Количество исправляемых ошибок = "))
        self.LabelTableFindEr.setText(_translate("MainWindow", "Количество обнаруживаемых ошибок = "))
        self.LabelWordInput.setText(_translate("MainWindow", "<html><head/><body><p>Введите входное слово</p></body></html>"))
        self.PushButtonDecode.setText(_translate("MainWindow", "Начать декодирование"))
        self.LabelTableSE.setText(_translate("MainWindow", "Таблица синдромов и векторов ошибок"))
        self.LabelSyndrom.setText(_translate("MainWindow", "<html><head/><body><p>S =</p></body></html>"))
        self.LabelErrorVector.setText(_translate("MainWindow", "<html><head/><body><p>e =</p></body></html>"))
        self.LabelCW.setText(_translate("MainWindow", "<html><head/><body><p>C =</p></body></html>"))
        self.LabelIW.setText(_translate("MainWindow", "<html><head/><body><p>i =</p></body></html>"))
        self.PushButtonCreateMatrix.setText(_translate("MainWindow", "Создать матрицу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
