import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelInputText = QtWidgets.QLabel(self.centralwidget)
        self.LabelInputText.setGeometry(QtCore.QRect(179, 10, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LabelInputText.setFont(font)
        self.LabelInputText.setObjectName("LabelInputText")
        self.TextEditInputText = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditInputText.setGeometry(QtCore.QRect(10, 40, 538, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditInputText.setFont(font)
        self.TextEditInputText.setObjectName("TextEditInputText")
        self.SpinBoxR = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxR.setGeometry(QtCore.QRect(10, 80, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBoxR.setFont(font)
        self.SpinBoxR.setReadOnly(False)
        self.SpinBoxR.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.SpinBoxR.setKeyboardTracking(False)
        self.SpinBoxR.setMinimum(2)
        self.SpinBoxR.setObjectName("SpinBoxR")
        self.PushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonStart.setGeometry(QtCore.QRect(70, 80, 478, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonStart.setFont(font)
        self.PushButtonStart.setObjectName("PushButtonStart")
        self.LabelK = QtWidgets.QLabel(self.centralwidget)
        self.LabelK.setEnabled(True)
        self.LabelK.setGeometry(QtCore.QRect(324, 115, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelK.setFont(font)
        self.LabelK.setObjectName("LabelK")
        self.LabelN = QtWidgets.QLabel(self.centralwidget)
        self.LabelN.setEnabled(True)
        self.LabelN.setGeometry(QtCore.QRect(224, 115, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelN.setFont(font)
        self.LabelN.setObjectName("LabelN")
        self.LabelR = QtWidgets.QLabel(self.centralwidget)
        self.LabelR.setEnabled(True)
        self.LabelR.setGeometry(QtCore.QRect(124, 115, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelR.setFont(font)
        self.LabelR.setObjectName("LabelR")
        self.LabelOutputBinaryTextIn = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputBinaryTextIn.setGeometry(QtCore.QRect(174, 220, 210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputBinaryTextIn.setFont(font)
        self.LabelOutputBinaryTextIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelOutputBinaryTextIn.setObjectName("LabelOutputBinaryTextIn")
        self.TextEditOutputBinaryTextIn = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputBinaryTextIn.setGeometry(QtCore.QRect(10, 250, 538, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputBinaryTextIn.setFont(font)
        self.TextEditOutputBinaryTextIn.setObjectName("TextEditOutputBinaryTextIn")
        self.LabelCodeSubwordsOrigins = QtWidgets.QLabel(self.centralwidget)
        self.LabelCodeSubwordsOrigins.setGeometry(QtCore.QRect(735, 10, 185, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelCodeSubwordsOrigins.setFont(font)
        self.LabelCodeSubwordsOrigins.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelCodeSubwordsOrigins.setObjectName("LabelCodeSubwordsOrigins")
        self.LabelCodeSubwordsErrors = QtWidgets.QLabel(self.centralwidget)
        self.LabelCodeSubwordsErrors.setGeometry(QtCore.QRect(735, 115, 185, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelCodeSubwordsErrors.setFont(font)
        self.LabelCodeSubwordsErrors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelCodeSubwordsErrors.setObjectName("LabelCodeSubwordsErrors")
        self.LabelOutputText = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputText.setGeometry(QtCore.QRect(204, 150, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputText.setFont(font)
        self.LabelOutputText.setObjectName("LabelOutputText")
        self.TextEditOutputText = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputText.setGeometry(QtCore.QRect(10, 180, 538, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputText.setFont(font)
        self.TextEditOutputText.setObjectName("TextEditOutputText")
        self.LabelOutputBinaryTextOut = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputBinaryTextOut.setGeometry(QtCore.QRect(722, 220, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputBinaryTextOut.setFont(font)
        self.LabelOutputBinaryTextOut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelOutputBinaryTextOut.setObjectName("LabelOutputBinaryTextOut")
        self.TextEditOutputBinaryTextOut = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputBinaryTextOut.setGeometry(QtCore.QRect(558, 250, 538, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputBinaryTextOut.setFont(font)
        self.TextEditOutputBinaryTextOut.setObjectName("TextEditOutputBinaryTextOut")
        self.TableWidgetCodeSubwordsOrigins = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetCodeSubwordsOrigins.setGeometry(QtCore.QRect(558, 40, 538, 65))
        self.TableWidgetCodeSubwordsOrigins.setObjectName("TableWidgetCodeSubwordsOrigins")
        self.TableWidgetCodeSubwordsOrigins.setColumnCount(0)
        self.TableWidgetCodeSubwordsOrigins.setRowCount(0)
        self.TableWidgetCodeSubwordsErrors = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetCodeSubwordsErrors.setGeometry(QtCore.QRect(558, 145, 538, 65))
        self.TableWidgetCodeSubwordsErrors.setObjectName("TableWidgetCodeSubwordsErrors")
        self.TableWidgetCodeSubwordsErrors.setColumnCount(0)
        self.TableWidgetCodeSubwordsErrors.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hamming code"))
        self.LabelInputText.setText(_translate("MainWindow", "Введите входное сообщение"))
        self.PushButtonStart.setText(_translate("MainWindow", "Запустить работу кодека"))
        self.LabelK.setText(_translate("MainWindow", "k ="))
        self.LabelN.setText(_translate("MainWindow", "n ="))
        self.LabelR.setText(_translate("MainWindow", "r ="))
        self.LabelOutputBinaryTextIn.setText(_translate("MainWindow", "Информационное слово (входное)"))
        self.LabelCodeSubwordsOrigins.setText(_translate("MainWindow", "Кодовые подслова без ошибок"))
        self.LabelCodeSubwordsErrors.setText(_translate("MainWindow", "Кодовые подслова c ошибками"))
        self.LabelOutputText.setText(_translate("MainWindow", "Выходное сообщение"))
        self.LabelOutputBinaryTextOut.setText(_translate("MainWindow", "Информационное слово (выходное)"))

