from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelInputMessage = QtWidgets.QLabel(self.centralwidget)
        self.LabelInputMessage.setGeometry(QtCore.QRect(190, 10, 172, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelInputMessage.setFont(font)
        self.LabelInputMessage.setObjectName("LabelInputMessage")
        self.TextEditInputMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditInputMessage.setGeometry(QtCore.QRect(10, 40, 530, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditInputMessage.setFont(font)
        self.TextEditInputMessage.setObjectName("TextEditInputMessage")
        self.SpinBoxFieldDimension = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxFieldDimension.setGeometry(QtCore.QRect(190, 80, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBoxFieldDimension.setFont(font)
        self.SpinBoxFieldDimension.setReadOnly(False)
        self.SpinBoxFieldDimension.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.SpinBoxFieldDimension.setKeyboardTracking(False)
        self.SpinBoxFieldDimension.setMinimum(2)
        self.SpinBoxFieldDimension.setObjectName("SpinBoxFieldDimension")
        self.PushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonStart.setGeometry(QtCore.QRect(250, 80, 290, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonStart.setFont(font)
        self.PushButtonStart.setObjectName("PushButtonStart")
        self.TextEditOutputResults = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputResults.setGeometry(QtCore.QRect(10, 115, 530, 165))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputResults.setFont(font)
        self.TextEditOutputResults.setObjectName("TextEditOutputResults")
        self.LabelInputFieldDimension = QtWidgets.QLabel(self.centralwidget)
        self.LabelInputFieldDimension.setGeometry(QtCore.QRect(10, 82, 170, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelInputFieldDimension.setFont(font)
        self.LabelInputFieldDimension.setObjectName("LabelInputFieldDimension")
        self.PushButtonGetTutorial = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonGetTutorial.setGeometry(QtCore.QRect(10, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.PushButtonGetTutorial.setFont(font)
        self.PushButtonGetTutorial.setObjectName("PushButtonGetTutorial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator in the fields"))
        self.LabelInputMessage.setText(_translate("MainWindow", "Введите входное выражение"))
        self.PushButtonStart.setText(_translate("MainWindow", "Вычислить выражение"))
        self.LabelInputFieldDimension.setText(_translate("MainWindow", "Выберите размерность поля"))
        self.PushButtonGetTutorial.setText(_translate("MainWindow", "?"))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
